### ISSUE TITLE
onRegionSelect - region is undefined

### ISSUE THREAD

**Issue by D1M** [manifestinteractive/jqvmap#201] opened 2016-01-18 09:51 UTC
onRegionClick: function(element, code, region) - region is defined.
onRegionSelect: function(element, code, region) - region is undefined for all codes.

**Comment by the-vector** [comment] 2016-02-01 20:42
@D1M 
Write it on the line 468
`regionClickEvent = $.Event('regionClick.jqvmap');`
After
`jQuery(params.container).trigger('regionClick.jqvmap', [code, mapData.pathes[code].name]);`

**Comment by manifestinteractive** [comment] 2016-02-04 22:02
Looks like something got lost there, I will take a look into why this did not get passed over.

**Comment by manifestinteractive** [comment] 2016-02-04 22:04
Can you verify if this issue is resolved in this branch ?

https://github.com/manifestinteractive/jqvmap/tree/v1.5.0_prerelease

**Comment by the-vector** [comment] 2016-02-04 23:26
@manifestinteractive
Doesn't work. It's my project [my_repository](https://github.com/the-vector/enviroment)
In the folder `'js/libs/jqvmap'`. working 'jquery.vmap.js'

**Closed** 2016-03-16 01:43 UTC
Labels: Bug Report

**Comment by Thoum** [comment] 2016-03-22 08:18
@manifestinteractive : Seems the issue is not solved, i still have the problem with the latest version.
The code is defined, but not the region.

**Comment by JeansReal** [comment] 2016-11-07 19:36
Same problem here
