### ISSUE TITLE
Dynamically updating labels

### ISSUE THREAD

**Issue by andreasspeck** [manifestinteractive/jqvmap#195] opened 2015-12-21 18:28 UTC
I have a jqvmap (#2vmapr - it's the second map on the same  page), and I need to dynamically update the labels on hover according to what someone selects elsewhere on the page (there is a year selector and depending on the year the labels for some countries will include a different summary).

From the documentation I get:

```js
jQuery('#vmap').bind('labelShow.jqvmap',
    function(event, label, code)
    {

    }
);
```

In my case that would be:

```js
jQuery('#2vmapr').bind('labelShow.jqvmap',
    function(event, label, code)
    {

    }
);
```

I have all the code in a long string, which I get into my Javascript function. The string includes a lot of statement such as if (code="us") { label.text('Arms importer'); } ...

If I put that statement above manually into the function, it seems to update all labels to "Arms Importer", and not just the one I need.

If I put in the just the string variable in which as a long row of if, else if statements, nothing happens.

```js
jQuery('#2vmapr').bind('labelShow.jqvmap',
    function(event, label, code)
    {
       labelstring2
    }
);
```

Any hints?

**Comment by manifestinteractive** [comment] 2015-12-21 19:13
@andreasspeck The issue seems like it might be because your ID starts with a number, which is actually not valid.  Pretty much all languages do not allow for variables to start with numbers, and HTML is no exception.

SEE:  https://css-tricks.com/ids-cannot-start-with-a-number/

Could you try changing `#2vmapr` to something like `#vmapr2` and see if that addresses your issues ?

**Comment by andreasspeck** [comment] 2015-12-21 23:35
I'll try that tomorrow - although in this case I doubt it. Updating the colours of the countries works fine, only the labels don't work.

**Comment by andreasspeck** [comment] 2015-12-22 08:35
The problem is not the ID (colours worked anyway), but I needed to do eval(labelstring2), so that the string is evaluated as a function. Doing that it works. Now just struggling with html in the labelstring (which I need).

**Comment by andreasspeck** [comment] 2015-12-22 08:45
It seems for my latter question I am hitting issue 28: https://github.com/manifestinteractive/jqvmap/issues/28

So I can't put html in a label? I would need the title, a text and a table.

**Comment by manifestinteractive** [comment] 2016-01-08 07:42
@andreasspeck I am looking into this right now.

**Comment by manifestinteractive** [comment] 2016-01-08 07:54
OK, so the issue is that you are using `label.text();` which literally manages text.  All you need to do for html is use label.html();  Here are a couple examples, that work 100% correctly with the current build.  I just added some region code logic as an example, but of course you are free to build your own HTML string :)

```js
onLabelShow: function(event, label, code){
    if (code == 'fl') {
        label.html('<div class="map-tooltip"><h1 class="header">Header</h1><p class="description">Some Description</p></div>');
    }
}
```

or with the bind method:

```js
jQuery('#2vmapr').bind('labelShow.jqvmap',
    function(event, label, code)
    {
        if (code == 'fl') {
            label.html('<div class="map-tooltip"><h1 class="header">Header</h1><p class="description">Some Description</p></div>');
        }
    }
);
```

Closing out this ticket as it is supported by our current version :)  I will, however, update the documentation better so people know how to set HTML rather than text, if they so choose.

**Closed by manifestinteractive** 2016-01-08 07:54 UTC
Labels: Question, Requires Further Attention

**Comment by manifestinteractive** [comment] 2016-01-08 08:14
Just a quick not for anyone reading this.  The `label` that is returned for `onLabelShow` is literally the DOM element itself as a jQuery Selector.  Meaning you can do anything you want with it just as you would with any other DOM Element, e.g. change background colors, inject HTML, change positions, etc.

Just keep in mind that you are controlling a single element on the page ( there is only one label, ever, its just getting updated depending on what you hover over ).  So, if you use jQuery to change the way that label works, it will affect ALL labels.  So you may want to setup a default to always revert to at the top of your `onLabelShow` function if you choose to go this route.

However, the easiest would just be to use HTML as listed in the example above.  This allows you to control the look of the label with CSS that you have prepared in your CSS file.

**Comment by andreasspeck** [comment] 2016-02-07 17:33
Sorry for coming back to this so late.
I can confirm this works fine! Thanks a lot for the clarification.
