### ISSUE TITLE
States without stroke... Brazil map only

### ISSUE THREAD

**Issue by wesleymacente** [manifestinteractive/jqvmap#228] opened 2016-05-09 15:22 UTC
The map of Brazil hasn't or almost hasn't a stroke/outline around states.
I tried to add outline options but not worked!
Are there any way to fix it?

![captura de tela 2016-05-09 as 11 18 16](https://cloud.githubusercontent.com/assets/2005241/15117997/3ef64e06-15d8-11e6-9767-00b23ae05389.png)

![captura de tela 2016-05-09 as 11 18 28](https://cloud.githubusercontent.com/assets/2005241/15117999/433c056e-15d8-11e6-8efb-c1c5397a2056.png)

**Comment by manifestinteractive** [comment] 2016-05-17 23:05
That certainly is weird.  I tried this to and it did not work.  It accepts the properties just fine so the issue is not in the javascript.  Likely there is an issue with the map file itself.  I will see if I can reach out to the original author of that file to see if they have any input on the issue.

**Comment by manifestinteractive** [comment] 2016-05-18 02:40
It looks like we had three versions of that brazil map.

What I could find regarding Pull Requests with that file changed was here:

https://github.com/manifestinteractive/jqvmap/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+brazil

The files appear to originate from Author @elmeerr back in 2013.  You will likely need to reach out to him to recreate the file since he was the last one to touch it.  It is definitely the map file though, after looking further into this.  It does not appear to have been generated with region borders like the other map files.

Honestly not sure how that was never noticed until now.

**Comment by elmeerr** [comment] 2016-05-19 14:49
@wesleymacente @manifestinteractive Hi guys! To be honest, I don't even remember how I create this file...for me it was ok but now I see the difference. So...I'm trying to build another one but, as I said...I don't recall how I get the data from shapefile...I'm trying use SVG without success until now...

I'll keep trying to fix it and appreciate if you guys can give any help.

See you soon.

Kind regards.

**Comment by elmeerr** [comment] 2016-05-19 17:06
I'm back....now with the solution:

![mapa_brazil](https://cloud.githubusercontent.com/assets/4071037/15402393/5427de6c-1dca-11e6-9adb-aa836dcab8b8.png)

I think that is good now, right? I also improve the JS file and reduce it from +2mb to 145kb.

If everything is fine, I think you can close the issue.

Kind regards.

**Comment by wesleymacente** [comment] 2016-05-19 17:57
Olá @elmeerr. Dei uma olhada na sua atualização e realmente as linhas entre os estados melhorou!
No meu caso eu uso outras opções como estados inativos... mouseover e etc e notei que o mapa não funcionou com estes options. 

Ah alguma forma de arrumar somente as linhas deixando os outros options funcionando?

Obrigado.

**Comment by elmeerr** [comment] 2016-05-19 20:03
@wesleymacente você tá querendo dizer que na outra versão do mapa você conseguia e nessa versão não consegue?

**Comment by wesleymacente** [comment] 2016-05-19 20:35
@elmeerr isso mesmo.

Assim:

![captura de tela 2016-05-19 as 16 34 40](https://cloud.githubusercontent.com/assets/2005241/15408724/a08e5fe6-1ddf-11e6-870f-64dbff97728a.png)

**Comment by elmeerr** [comment] 2016-05-19 21:35
@wesleymacente você pode colocar o exemplo do `html `e do `js `que você ta usando no [Fiddle](https://jsfiddle.net/) ou no [CodePen](https://codepen.io/pen/) para que eu possa ver o que ta acontecendo? Porque eu só alterei o arquivo que gera o desenho do mapa, as funções do mapa fazem parte do framework `jquery.jqvmap.js`...testei aqui e as funções estão funcionando normalmente.

**Comment by wesleymacente** [comment] 2016-05-20 14:14
Segue @elmeerr 
https://jsfiddle.net/wesleymacente/d8jpe3d7/1/

**Comment by elmeerr** [comment] 2016-05-20 17:19
Oi @wesleymacente acho que o problema é porque atualizei também os códigos dos estados. Invés dos "br-xx" agora é só usar as siglas dos estados mesmo. Testa aí e me avisa. Flw.

**Comment by wesleymacente** [comment] 2016-05-20 18:45
Nossa.. que mancada!
Perfeito @elmeerr ... vc arrumou os strokes e ainda facilitou na nomeação dos estados!

Vlw dmais!!

**Closed** 2016-05-20 18:45 UTC
Labels: Bug Report, Map File
